### ISSUE TITLE
NPM Install Error

### ISSUE THREAD

**Issue by eljefe6a** [mermaidjs/mermaid.cli#1]
When installing on Ubuntu 17.04, I get:

```
sudo npm install -g mermaid.cli
/usr/bin/mmdc -> /usr/lib/node_modules/mermaid.cli/index.js

> puppeteer@0.10.2 install /usr/lib/node_modules/mermaid.cli/node_modules/puppeteer
> node install.js

fs.js:892
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/mermaid.cli/node_modules/puppeteer/.local-chromium'
    at Object.fs.mkdirSync (fs.js:892:18)
    at Object.downloadRevision (/usr/lib/node_modules/mermaid.cli/node_modules/puppeteer/utils/ChromiumDownloader.js:97:10)
    at Object.<anonymous> (/usr/lib/node_modules/mermaid.cli/node_modules/puppeteer/install.js:33:12)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:201:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@0.10.2 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@0.10.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/eljefe6a/.npm/_logs/2017-09-13T15_40_16_847Z-debug.log
```

**Comment by tylerlong** [comment]
https://github.com/GoogleChrome/puppeteer/issues/375

https://docs.npmjs.com/getting-started/fixing-npm-permissions

I think this is a general npm issue.

You can also install it locally then invoke it via './node_modules/.bin/mmdc'.

Feel free to reopen if you still have issues.

**Comment by eljefe6a** [comment]
Installing with yarn worked.
