### ISSUE TITLE
Error Incorrect usage of "merge". 

### ISSUE THREAD

**Issue by ahmad88me** [mermaidjs/mermaid.cli#115]
mmdc -i input.mmd -o output.png

file: `input.mmd`
```
gitGraph
    merge feature
```

Error:
```
Error: Evaluation failed: Error: Incorrect usage of "merge". Current branch (main)has no commits
    at pptr://__puppeteer_evaluation_script__:21:17
    at ExecutionContext._ExecutionContext_evaluate (file:///usr/local/lib/node_modules/@mermaid-js/mermaid-cli/node_modules/puppeteer-core/lib/esm/puppeteer/common/ExecutionContext.js:225:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async ExecutionContext.evaluate (file:///usr/local/lib/node_modules/@mermaid-js/mermaid-cli/node_modules/puppeteer-core/lib/esm/puppeteer/common/ExecutionContext.js:104:16)
    at async ElementHandle.evaluate (file:///usr/local/lib/node_modules/@mermaid-js/mermaid-cli/node_modules/puppeteer-core/lib/esm/puppeteer/common/JSHandle.js:86:16)
    at async ElementHandle.$eval (file:///usr/local/lib/node_modules/@mermaid-js/mermaid-cli/node_modules/puppeteer-core/lib/esm/puppeteer/common/ElementHandle.js:138:24)
    at async renderMermaid (file:///usr/local/lib/node_modules/@mermaid-js/mermaid-cli/src/index.js:204:22)
    at async parseMMD (file:///usr/local/lib/node_modules/@mermaid-js/mermaid-cli/src/index.js:176:20)
    at async run (file:///usr/local/lib/node_modules/@mermaid-js/mermaid-cli/src/index.js:418:20)
    at async cli (file:///usr/local/lib/node_modules/@mermaid-js/mermaid-cli/src/index.js:142:3)
```

**Comment by ahmad88me** [comment]
I also tried to install it locally and I got the same error

**Comment by aloisklink** [comment]
Development has moved to the https://github.com/mermaid-js/mermaid-cli repo, please re-open your issue there if it's still relevant.
The package has also been renamed on NPM to [`@mermaid-js/mermaid-cli`](https://www.npmjs.com/package/@mermaid-js/mermaid-cli), so you may need to run `npm uninstall mermaid.cli && npm install @mermaid-js/mermaid-cli` to get the latest version of this package.

FYI, if you want to `merge feature`, you first need to make a `feature` branch, so something like:

````markdown
```mermaid
gitGraph
  commit "initial commit"
  branch feature
  commit "this branch is on feature"
  checkout main
  merge feature
```
````

will create

```mermaid
gitGraph
  commit "initial commit"
  branch feature
  commit "this branch is on feature"
  checkout main
  merge feature
```
