### ISSUE TITLE
Cannot parse participant with dash in sequence diagram

### ISSUE THREAD

**Issue by lmcthbe** [mermaidjs/mermaid.cli#56]
The following syntax "participant API (test-dev)" failed with:

(node:9217) UnhandledPromiseRejectionWarning: Error: Evaluation failed: Error: Lexical error on line 5. Unrecognized text.
...rth    participant API (test-dev)   
----------------------^
    at x.parseError (file:///Users/tbeauquier/mermaid.cli/node_modules/mermaid.cli/mermaid.min.js:1:423219)
    at Object.parseError (file:///Users/tbeauquier/mermaid.cli/node_modules/mermaid.cli/mermaid.min.js:1:425417)
    at Object.next (file:///Users/tbeauquier/mermaid.cli/node_modules/mermaid.cli/mermaid.min.js:1:429413)
    at Object.lex (file:///Users/tbeauquier/mermaid.cli/node_modules/mermaid.cli/mermaid.min.js:1:429580)
    at Object.lex (file:///Users/tbeauquier/mermaid.cli/node_modules/mermaid.cli/mermaid.min.js:1:429602)
    at x.parse (file:///Users/tbeauquier/mermaid.cli/node_modules/mermaid.cli/mermaid.min.js:1:423938)
    at Object.e.draw (file:///Users/tbeauquier/mermaid.cli/node_modules/mermaid.cli/mermaid.min.js:1:720085)
    at Object.render (file:///Users/tbeauquier/mermaid.cli/node_modules/mermaid.cli/mermaid.min.js:1:760928)
    at s (file:///Users/tbeauquier/mermaid.cli/node_modules/mermaid.cli/mermaid.min.js:8:233)
    at Object.init (file:///Users/tbeauquier/mermaid.cli/node_modules/mermaid.cli/mermaid.min.js:8:318)
    at ExecutionContext.evaluateHandle (/Users/tbeauquier/mermaid.cli/node_modules/puppeteer/lib/ExecutionContext.js:88:13)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)

**Comment by dascarlet** [comment]
@lmcthbe You can do like this.
`participant api as API (test-dev)`

I guess Mermaid doesn't recognize `-` as `participant` syntax.

**Comment by aloisklink** [comment]
Development has moved to the https://github.com/mermaid-js/mermaid-cli repo, please re-open your issue there if it's still relevant.
The package has also been renamed on NPM to [`@mermaid-js/mermaid-cli`](https://www.npmjs.com/package/@mermaid-js/mermaid-cli), so you may need to run `npm uninstall mermaid.cli && npm install @mermaid-js/mermaid-cli` to get the latest version of this package.
