### ISSUE TITLE
Hexagon node syntax leads to UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by ismarslomic** [mermaidjs/mermaid.cli#76]
When using [Hexagon Node syntax](https://mermaid-js.github.io/mermaid/#/flowchart?id=a-hexagon-node) in input file MermaidJS CLI (`v0.5.1`) throws `UnhandledPromiseRejectionWarning` and the whole process hangs.

**input.mmd**
```
graph LR
    id1{{This is the text in the box}}
```

**command**
`mmdc -i input.mmd -o output.png`

**error message**
```
(node:95078) UnhandledPromiseRejectionWarning: Error: Evaluation failed: Error: Parse error on line 2:
graph LR    id1{{This is the text in
----------------^
Expecting 'SPACE', 'GRAPH', 'DIR', 'TAGEND', 'TAGSTART', 'UP', 'DOWN', 'subgraph', 'end', 'MINUS', '--', '==', 'STR', 'STYLE', 'LINKSTYLE', 'CLASSDEF', 'CLASS', 'CLICK', 'DEFAULT', 'NUM', 'PCT', 'COMMA', 'ALPHA', 'COLON', 'BRKT', 'DOT', 'PUNCTUATION', 'UNICODE_TEXT', 'PLUS', 'EQUALS', 'MULT', got 'DIAMOND_START'
    at Yt.parseError (file:///Users/john.doe/.config/yarn/global/node_modules/mermaid.cli/mermaid.min.js:1:486512)
    at Yt.parse (file:///Users/john.doe/.config/yarn/global/node_modules/mermaid.cli/mermaid.min.js:1:487678)
    at Object.e.getClasses (file:///Users/john.doe/.config/yarn/global/node_modules/mermaid.cli/mermaid.min.js:1:749437)
    at Object.render (file:///Users/john.doe/.config/yarn/global/node_modules/mermaid.cli/mermaid.min.js:1:759998)
    at s (file:///Users/john.doe/.config/yarn/global/node_modules/mermaid.cli/mermaid.min.js:8:233)
    at Object.init (file:///Users/john.doe/.config/yarn/global/node_modules/mermaid.cli/mermaid.min.js:8:318)
    at __puppeteer_evaluation_script__:17:20
    at ExecutionContext._evaluateInternal (/Users/john.doe/.config/yarn/global/node_modules/puppeteer/lib/ExecutionContext.js:122:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (/Users/john.doe/.config/yarn/global/node_modules/puppeteer/lib/ExecutionContext.js:48:12)
    at async ElementHandle.evaluate (/Users/john.doe/.config/yarn/global/node_modules/puppeteer/lib/JSHandle.js:55:12)
    at async ElementHandle.$eval (/Users/john.doe/.config/yarn/global/node_modules/puppeteer/lib/JSHandle.js:478:20)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/Users/john.doe/.config/yarn/global/node_modules/puppeteer/lib/helper.js:111:15)
    at ElementHandle.evaluate (/Users/john.doe/.config/yarn/global/node_modules/puppeteer/lib/JSHandle.js:55:42)
    at ElementHandle.<anonymous> (/Users/john.doe/.config/yarn/global/node_modules/puppeteer/lib/helper.js:112:23)
    at ElementHandle.$eval (/Users/john.doe/.config/yarn/global/node_modules/puppeteer/lib/JSHandle.js:478:40)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
  -- ASYNC --
    at ElementHandle.<anonymous> (/Users/john.doe/.config/yarn/global/node_modules/puppeteer/lib/helper.js:111:15)
    at DOMWorld.$eval (/Users/john.doe/.config/yarn/global/node_modules/puppeteer/lib/DOMWorld.js:156:21)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
  -- ASYNC --
    at Frame.<anonymous> (/Users/john.doe/.config/yarn/global/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.$eval (/Users/john.doe/.config/yarn/global/node_modules/puppeteer/lib/Page.js:347:29)
    at Page.<anonymous> (/Users/john.doe/.config/yarn/global/node_modules/puppeteer/lib/helper.js:112:23)
    at /Users/john.doe/.config/yarn/global/node_modules/mermaid.cli/index.bundle.js:83:14
    at Generator.next (<anonymous>)
    at step (/Users/john.doe/.config/yarn/global/node_modules/mermaid.cli/index.bundle.js:4:191)
    at /Users/john.doe/.config/yarn/global/node_modules/mermaid.cli/index.bundle.js:4:361
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:95078) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:95078) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Alien2150** [comment]
Having the same issue with stadium/db shaped like graphs:

`db[( database )]` or `B([Stadium])`

(node:52069) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Evaluation failed: Error: Parse error on line 2:
graph LR    db[( database )]
---------------^
Expecting 'SPACE', 'GRAPH', 'DIR', 'TAGEND', 'TAGSTART', 'UP', 'DOWN', 'subgraph', 'end', 'MINUS', '--', '==', 'STR', 'STYLE', 'LINKSTYLE', 'CLASSDEF', 'CLASS', 'CLICK', 'DEFAULT', 'NUM', 'PCT', 'COMMA', 'ALPHA', 'COLON', 'BRKT', 'DOT', 'PUNCTUATION', 'UNICODE_TEXT', 'PLUS', 'EQUALS', 'MULT', got 'PS'

**Comment by aloisklink** [comment]
Development has moved to the https://github.com/mermaid-js/mermaid-cli repo, please re-open your issue there if it's still relevant.
The package has also been renamed on NPM to [`@mermaid-js/mermaid-cli`](https://www.npmjs.com/package/@mermaid-js/mermaid-cli), so you may need to run `npm uninstall mermaid.cli && npm install @mermaid-js/mermaid-cli` to get the latest version of this package.
